### ISSUE TITLE
Proximity flow not responding

### ISSUE THREAD

**Issue by maurolucc** [eu-digital-identity-wallet/eudi-lib-ios-iso18013-data-transfer#37]
Hello!

**Context**: I'm trying to test the [Proximity flow](https://github.com/eu-digital-identity-wallet/eudi-app-ios-wallet-ui?tab=readme-ov-file#proximity-flow) following the instructions provided. Once the wallet is successfully build on an iPhone, I load the sample data provided and click on show QR code.

**Problem**: The EUDI Verifier app detects the QR code and shows "Device engagement received..." message. After a while, it shows a toast "Error connecting holder" and nothing happens in the wallet. I've seen in the demo video that this flow works on Eudi app Android wallet. Is it currently working fot Eudi app iOS wallet?

Versions tested:

- Wallet: code built at this [commit](cff9e9fdaa1fe6497aaf11b52e51223fd3dbe60b)
- Verifier: [version 2.4](https://install.appcenter.ms/orgs/eu-digital-identity-wallet/apps/mdoc-verifier-testing/distribution_groups/eudi%20verifier%20(testing)%20public)
- Verifier options combinations:  BLE central client mode, BLE peripheral server mode, BLE central client mode + BLE peripheral server mode.

Thanks in advance

**Comment by phisakel** [comment]
Hi @maurolucc, thanks for the issue. I have an iPhone SE3 and is working fine. Please note that the BLE peripheral **server** mode must be activated. You can try also to regenerate the QR in the iPhone if it is not reading.

**Comment by maurolucc** [comment]
Hi there,

Apologies for the delay in responding—I’ve been out of the office for a while. I’ve recently tested this flow using an iPhone 16, and I’m no longer encountering the issue. I’m able to proceed with my work, so from our side, you can go ahead and close this issue.

Thank you for your support!
